require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'VoiceitReactNativeDemo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-voiceit', :path => '../node_modules/react-native-voiceit'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  pod "VoiceIt3-IosSDK", '~> 2.2.6'

  target 'VoiceitReactNativeDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'VoiceitReactNativeDemo-tvOS' do
  # Pods for VoiceitReactNativeDemo-tvOS

  target 'VoiceitReactNativeDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
